name: Continuous Integration and Continuous Deployment

on:
    push:
        branches:
            - master

jobs :
    builds :
        runs-on : ubuntu-latest
        steps:
            - name : Check out Code 
              uses: actions/checkout@v2
            
            -   name : Setup . Net 6
                uses : actions/setup-dotnet@v1
                with:
                    dotnet-version : '6.0.x'
            
            - name : Restore Dependencies
              run : dotnet restory

            - name : Build App 
              run : dotnet build -c Release --no-restore
              

        
 
        